namespace RazorSharp.CoreJit
{
	internal enum CorInfoCallKind
	{
		CORINFO_CALL,
		CORINFO_CALL_CODE_POINTER,
		CORINFO_VIRTUALCALL_STUB,
		CORINFO_VIRTUALCALL_LDVIRTFTN,
		CORINFO_VIRTUALCALL_VTABLE
	}
}